# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cookies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Alamofire', '5.6.2'
    pod 'NMapsMap','3.10.0'

  # Pods for Cookies

  target 'CookiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CookiesUITests' do
    # Pods for testing
  end

end
